name: Deploy Gateway to Azure App Service

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
    paths:
      - 'Gateway/**'  # Trigger only when there are changes in the Gateway project

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Ensure this matches your project's target .NET version

      - name: Build with dotnet
        run: dotnet build src/Gateway/Gateway.csproj --configuration Release  # Specify the path to the Gateway project's .csproj file

      - name: Dotnet publish
        run: dotnet publish src/Gateway/Gateway.csproj -c Release -o ./publish  # Publish the Gateway project

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_GATEWAY }}  # Use the Azure App Service name for your Gateway app
          publish-profile: ${{ secrets.AZURE_CREDENTIALS_GATEWAY }}  # Use the publish profile or service principal for Azure deployment
          package: ./publish
