name: Deploy Gateway to Azure App Service

on:
  push:
    branches:
      - master  # Adjust if your default branch is different
    paths:
      - 'Gateway/**'  # Ensure this matches the path to your Gateway project

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      # Debugging step: List contents of the Gateway directory
      - name: List contents of the Gateway project directory
        run: dir
        working-directory: bt-net-assignment-romans/src/Gateway  # Adjust if your Gateway project is in a different directory

      
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_GATEWAY }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS_GATEWAY }}
          package: ./publish
